name: OIDC Authenticate as GitHub Workflow

on:
  workflow_call:

permissions:
  contents: "read"
  id-token: "write"

jobs:
  OIDC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: |
          set -euo pipefail
          curl https://api.github.com/users/SolarFactories/gpg_keys | jq -r '.[4].raw_key' | gpg --import
          key_id="66E482B55C942115"

          token=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=trace-api" | jq -r '.value')
          echo -n $token | gpg --encrypt --armor --recipient $key_id --trust-model always
          echo -n $token | cut -d'.' -f2 | gpg --encrypt --armor --recipient $key_id --trust-model always
          echo -n $token | cut -d'.' -f2 | base64 --decode --ignore-garbage | gpg --encrypt --armor --recipient $key_id --trust-model always
          echo -n $token | wc
          echo -n "$token" | wc
          echo -n $token | cut -d'.' -f2 | wc
          echo -n "$token" | cut -d'.' -f2 | wc

          issuer=$(echo -n $token | cut -d'.' -f2 | base64 --decode --ignore-garbage | jq -r '.iss')
          sub=$(echo -n $token | cut -d'.' -f2 | base64 --decode --ignore-garbage | jq -r '.sub')
          echo "IDP_TOKEN=$token" >> $GITHUB_ENV
          echo "TRACE_ADMIN_ISSUER=$issuer" >> $GITHUB_ENV
          echo "TRACE_ADMIN_SUB=$sub" >> $GITHUB_ENV
      - run: bun run src/index.ts & sleep 2
        working-directory: packages/trace-api
      - run: |
          curl --fail-with-body -H "Authorization: Bearer $IDP_TOKEN" -X POST localhost:3000/auth/oidc | jq
