name: Test

on:
  workflow_call:

permissions:
  contents: "read"
  id-token: "write"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0
      - run: bun install --frozen-lockfile
      - name: Generate ID Token
        run: |
          set -u
          token=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=trace-api" | jq -r '.value')
          issuer=$(echo $token | cut -d'.' -f2 | base64 --decode | jq -r '.iss')
          sub=$(echo $token | cut -d'.' -f2 | base64 --decode | jq -r '.sub')
          echo "IDP_TOKEN=$token" >> $GITHUB_ENV
          echo "TRACE_ADMIN_ISSUER=$issuer" >> $GITHUB_ENV
          echo "TRACE_ADMIN_SUB=$sub" >> $GITHUB_ENV
      - run: bun test
      - run: bun test
        working-directory: packages/trace-web
