name: Software Bill Of Materials

on:
  workflow_call:

permissions:
  contents: "read"

jobs:
  Cdxgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
      - run: bun install --frozen-lockfile --production
      - run: |
          bun install --global @cyclonedx/cdxgen
          cdxgen -o bom.json
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: "SBOM"
          path: "bom.json"
          if-no-files-found: "error"
          include-hidden-files: false
